export const NAV_LINKS = [
  "About",
  "Skills",
  "Experience",
  "Projects",
  "Contact",
];

export const SKILLS_FEATURED = [
  {
    icon: "▲",
    name: "Next.js",
    desc: "App Router v13–15, SSR/SSG/ISR, Server Components",
  },
  {
    icon: "⚛️",
    name: "React.js",
    desc: "Advanced hooks, performance, component architecture",
  },
  {
    icon: "🔷",
    name: "TypeScript",
    desc: "Strict typing, generics, utility types",
  },
  { icon: "📦", name: "Redux Toolkit", desc: "Normalized slices, entity adapters, RTK" },
  {
    icon: "🔄",
    name: "TanStack Query",
    desc: "Server state, caching, data-fetching",
  },
  { icon: "🟢", name: "Node.js", desc: "REST APIs, auth, real-time backends" },
];

export const EXPERIENCE = [
  {
    company: "Alphavima Technologies",
    role: "Associate Engineer",
    period: "Jul 2024 – Apr 2026",
    live: false,
    color: "#0a84ff",
    bg: "linear-gradient(135deg,#0a1628,#0d1e40)",
    icon: "🏢",
    highlights: [
      { metric: "+25%", desc: "Faster render times" },
      { metric: "−35%", desc: "Smaller bundle size" },
      { metric: "96+", desc: "Lighthouse scores" },
    ],
    bullets: [
      "Engineered a React + TypeScript Asset Availability Tracker with reusable component architecture, grid views, and dynamic filters — reduced asset lookup time by 30% for enterprise teams managing 1,000+ assets.",
      "Architected scalable state management using Redux Toolkit with normalized slice patterns and entity adapters across a configurable Kanban board spanning 3+ Dataverse entities — cut feature build time by ~40%.",
      "Integrated AI suggestion agents into a CRM chat UI using React with state-managed conversation logs — reduced manual lookup time by ~35% by surfacing automated recommendations inline.",
      "Built custom PCF Controls in React for Microsoft Dynamics 365 — extended native CRM capabilities with interactive components integrated into enterprise workflows across multiple clients.",
      "Optimized React bundle size and runtime performance via lazy loading, useMemo/useCallback, and code-splitting — achieved 25% faster render times, 35% smaller bundles, and Lighthouse scores of 96+.",
      "Monitored and improved Core Web Vitals (LCP, CLS, INP) using Lighthouse CI and Chrome DevTools across all deployed products.",
      "Delivered responsive layouts supporting 5+ screen sizes — increased mobile session length by 18%.",
    ],
  },
  {
    company: "Artificial Techligence",
    role: "Full Stack Web Developer Intern",
    period: "Feb 2024 – May 2024",
    live: false,
    color: "#30d158",
    bg: "linear-gradient(135deg,#0a1a14,#0d2818)",
    icon: "🚀",
    highlights: [
      { metric: "750+", desc: "Users secured via JWT" },
      { metric: "+30%", desc: "Response efficiency gained" },
      { metric: "AWS", desc: "Scalable portal deployment" },
    ],
    bullets: [
      "Built pixel-perfect React components from Figma specs using TailwindCSS — maintained design system token consistency across the full product with zero design regression.",
      "Developed a support ticket system frontend with React + Node.js REST APIs featuring real-time status tracking — improved team response efficiency by 30%.",
      "Implemented role-based JWT + OAuth authentication UI in React — secured access flows for 750+ users with clear error states and role-specific interface rendering.",
      "Contributed to a CI/CD-deployed, AWS-hosted internship portal — shipped a responsive, accessible frontend with scalable component architecture.",
    ],
  },
  {
    company: "Independent",
    role: "Freelance Frontend Developer",
    period: "Jun 2022 – Jan 2024",
    live: false,
    color: "#ff9f0a",
    bg: "linear-gradient(135deg,#241803,#2e1f0a)",
    icon: "💼",
    highlights: [
      { metric: "100%", desc: "Client satisfaction" },
      { metric: "React", desc: "Web apps delivered" },
      { metric: "Vite", desc: "Modern tooling mastery" },
    ],
    bullets: [
      "Delivered React-based web applications for local businesses with responsive design, reusable component libraries, and performance optimization — maintained 100% client satisfaction.",
      "Built foundational expertise in JavaScript, React, and modern tooling (Vite, ESM, bundling) through applied project work.",
    ],
  },
];

export const PROJECTS = [
  {
    name: "HasaBoard",
    tagline: "AI-Powered Client Onboarding SaaS.",
    desc: "Built an all-in-one client onboarding platform consolidating intake, contract signing, and deposit payments into a single branded flow — eliminating 3 separate tools with multi-currency payments and automated e-signature workflows.",
    emoji: "📋",
    chips: ["React", "TailwindCSS", "Node.js", "PostgreSQL", "DocuSeal", "Razorpay", "Stripe", "WhatsApp API"],
    grad: "linear-gradient(135deg,#0a2e1f 0%,#1a2e1f 50%,#0a1411 100%)",
    accent: "#34c759",
    metrics: [
      ["Onboarding", "−60% time"],
      ["Payments", "Stripe/Razorpay"],
      ["Disputes", "Zero in beta"],
    ],
  },
  {
    name: "OpenResumeCraft",
    tagline: "Privacy-First AI Resume Builder.",
    desc: "Engineered a privacy-first AI resume builder with 100% local model inference via Ollama — all user data stays on-device. Features a deterministic 6-dimension keyword-matching engine and a real-time ATS score dashboard.",
    emoji: "📄",
    chips: ["React", "Node.js", "Express", "Ollama", "OpenAI API"],
    grad: "linear-gradient(135deg,#2e1f0a 0%,#2e1a0f 50%,#14110a 100%)",
    accent: "#ff9f0a",
    metrics: [
      ["Inference", "100% Local"],
      ["ATS Match", "+35%"],
      ["Layout Errors", "−100%"],
    ],
  },
  {
    name: "TennChat",
    tagline: "Real-Time Chat Application.",
    desc: "Built a full-stack real-time messaging platform end-to-end with bidirectional communication, JWT auth, role-based controls, and Redux state management.",
    emoji: "💬",
    chips: ["React", "Redux", "TypeScript", "Socket.IO", "Node.js", "MongoDB"],
    grad: "linear-gradient(135deg,#0f1a3a 0%,#1a0f3a 50%,#0f1a3a 100%)",
    accent: "#5ac8fa",
    metrics: [
      ["Real-time", "WebSockets"],
      ["Auth", "JWT+Roles"],
      ["Testing", "Jest+RTL"],
    ],
  },
  {
    name: "AI Article Summarizer",
    tagline: "Any article. Under 8 seconds.",
    desc: "Built an AI-powered article summarizer integrating a third-party NLP REST API. Delivered summaries under 8s with cookie-based caching for efficiency.",
    emoji: "🤖",
    chips: ["React", "TypeScript", "Node.js", "REST API", "Cookie Storage"],
    grad: "linear-gradient(135deg,#0a1a2e 0%,#1a1a2e 50%,#0a1428 100%)",
    accent: "#bf5af2",
    metrics: [
      ["Speed", "<8 sec"],
      ["Efficiency", "+15%"],
      ["Cache", "Cookies"],
    ],
  },
];

export const ALL_SKILLS = [
  "JavaScript (ES6+)",
  "TypeScript",
  "HTML5 & CSS3",
  "SCSS",
  "React.js",
  "Next.js",
  "React Hooks",
  "Node.js",
  "Express.js",
  "PostgreSQL",
  "MongoDB",
  "Redux Toolkit",
  "TanStack Query",
  "Redux-Saga",
  "React Context API",
  "TailwindCSS",
  "GraphQL",
  "REST APIs",
  "Core Web Vitals",
  "Lighthouse CI",
  "JWT & OAuth",
  "AWS",
  "Azure",
  "Microsoft Dynamics 365",
  "PCF Controls",
  "CI/CD",
  "Git & GitHub",
  "Vite",
  "Razorpay & Stripe",
  "Twilio WhatsApp API",
  "DocuSeal",
  "Ollama & OpenAI API",
  "Jest & RTL",
];
